"""Cross-post a Kauli blog post to Medium, with a canonical link back to
the real Kauli URL - that backlink is the actual SEO/referral point of
doing this at all (a reader on Medium who clicks through, and search
engines treating the Kauli post as the "real" original rather than Medium
getting credit for duplicate content).

Uses Medium's REST API with a personal Integration Token (Medium's
account-level API key, generated by a real human from their own Medium
Settings -> Security and apps -> Integration tokens - never something
this app can create or fake on someone's behalf). Medium's public API
has been in "maintenance mode" for a while (no new accounts get fresh
developer OAuth apps) but the integration-token posting endpoint used
here is still real and still works - this hasn't been exercised against
a real Medium account in this session (no token available to test with),
so treat the exact request/response shape as worth double-checking the
first time this actually runs, the same honest caveat as the Calendly
webhook receiver.

Real, working code the moment MEDIUM_INTEGRATION_TOKEN is set - not
functional without it, and callers should check medium_configured()
first rather than let this fail confusingly deep inside a request.
"""
from __future__ import annotations

import os

import httpx

MEDIUM_API_BASE = "https://api.medium.com/v1"


def medium_configured() -> bool:
    return bool(os.environ.get("MEDIUM_INTEGRATION_TOKEN"))


def _headers() -> dict:
    token = os.environ.get("MEDIUM_INTEGRATION_TOKEN")
    return {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Accept-Charset": "utf-8",
    }


def publish_post(title: str, body_html: str, canonical_url: str, tags: list[str] | None = None) -> dict:
    """Returns {"ok": True, "url": "..."} on success, {"ok": False,
    "error": "..."} on failure - callers should always check "ok" before
    trusting "url" to exist. Never raises for an ordinary API failure
    (missing token, Medium rejecting the request, network error) - those
    are all real possibilities the caller needs to show the staff member,
    not a 500 page."""
    if not medium_configured():
        return {"ok": False, "error": "MEDIUM_INTEGRATION_TOKEN isn't set - nothing to publish with."}
    try:
        with httpx.Client(timeout=20) as client:
            me = client.get(f"{MEDIUM_API_BASE}/me", headers=_headers())
            me.raise_for_status()
            author_id = me.json()["data"]["id"]

            resp = client.post(
                f"{MEDIUM_API_BASE}/users/{author_id}/posts",
                headers=_headers(),
                json={
                    "title": title,
                    "contentFormat": "html",
                    "content": body_html,
                    "canonicalUrl": canonical_url,
                    "tags": (tags or [])[:5],  # Medium's own documented cap
                    "publishStatus": "public",
                },
            )
            resp.raise_for_status()
            return {"ok": True, "url": resp.json()["data"]["url"]}
    except httpx.HTTPStatusError as exc:
        detail = exc.response.text[:300] if exc.response is not None else str(exc)
        return {"ok": False, "error": f"Medium rejected the request ({exc.response.status_code}): {detail}"}
    except httpx.HTTPError as exc:
        return {"ok": False, "error": f"Couldn't reach Medium: {exc}"}
    except (KeyError, ValueError) as exc:
        return {"ok": False, "error": f"Unexpected response shape from Medium: {exc}"}
